# Group 16

# Team members:

# Zenan Ji (Student ID: 1122396) - city: Nanjing

# Weijie Ye (Student ID: 1160818) - city: Fuzhou

# Wenqin Liu (Student ID: 807291) - city: Guangdong

# Jinhong Yong (Student ID: 1198833) - city: Kuala Lumpur

# Zixuan Zeng (Student ID: 1088297) - city: Melbourne
---

volumes:
  - device: /dev/vdb
    mountpoint: /data
  - device: /dev/vdc
    mountpoint: /var/lib/docker

proxy_env:
  HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  http_proxy: http://wwwproxy.unimelb.edu.au:8000/
  https_proxy: http://wwwproxy.unimelb.edu.au:8000/
  no_proxy: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au  

# CouchDB configuration
user: admin
pass: "data-miner!"
VERSION: '3.1.1'
cookie: 'gQ7wygusPdkybBsmMr4uwGXq'
uuid: '5CBC6EFF-45E9-4981-B300-D40782BA0B26'
# cluster_name: '_cluster_setup'
# couchdb_container_name: 'couchdb_'
# couchdb_port: 5984
