# Prerequisites
# Instance Flavor: uom.mse.2c9g
# Available Zone: melbourne-qh2-uom
# Image Id: Ubuntu 20.04 LTS

# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: db_1
    vol_size: 40
  - vol_name: db_2
    vol_size: 40
  - vol_name: db_3
    vol_size: 40
  - vol_name: db_4
    vol_size: 40
  - vol_name: persistent
    vol_size: 90

# Instance
instances:
  - name: server1
    volumes: ['db_1', 'persistent']
    description: server1
  - name: server2
    volumes: ['db_2']
    description: server2
  - name: server3
    volumes: ['db_3']
    description: server3

instances2:
  - name: server4
    volumes: ['db_4']
    description: server4

# Ubuntu 20.04 LTS (Focal) amd64
instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: COMP90024
instance_flavor: uom.mse.2c9g
instance_flavor2: uom.mse.1c4g

server_list: []
volume_ids: []

volume_path: /volume
backup_path: /backup

# Security group
security_groups:
  - name: administration
    description: "Security group for server administration and remote access (e.g. access via SSH or HTTP for Frontend)"
  - name: intra_cluster_communication
    description: "Security group for communication between CouchDB nodes in cluster"

security_group_rules_public: 
  - name: administration
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0

security_group_rules_private: 
  - name: intra_cluster_communication
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_group: intra_cluster_communication
  - name: intra_cluster_communication
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_group: intra_cluster_communication
  - name: intra_cluster_communication
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_group: intra_cluster_communication

  