# Install Docker and CouchDB
- hosts: DataNodes
  vars_files:
    - host_vars/couchdb_settings.yaml
  gather_facts: true

  roles:
    - role: couchdb-setup

 # Perform CouchDB configuration on all hosts except Masternode
- hosts: DataNodes:!Masternode
  vars_files:
    - host_vars/couchdb_settings.yaml
  gather_facts: true

  roles:
    - role: couchdb-finish-setup

 # Perform CouchDB replicate on masternode
- hosts: DataNodes
  vars_files:
    - host_vars/couchdb_settings.yaml
  gather_facts: true

  roles:
    - role: couchdb-replicate