# Install Docker and CouchDB
- hosts: DataNodes
  vars_files:
    - host_vars/couchdb_settings.yaml
  gather_facts: true

  roles:
    # - role: nodes-common
    # - role: nodes-docker-install
    # - role: nodes-volume-mount
    - role: couchdb-setup

 # Perform CouchDB configuration on all hosts except Masternode
- hosts: DataNodes:!Masternode
  vars_files:
    - host_vars/couchdb_settings.yaml
  gather_facts: true

  roles:
    - role: couchdb-finish-setup