---
- hosts: database
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true
  roles:
    - role: deploy-couchdb

- hosts: mainnode
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true
  roles:
    - role: deploy-couchdb-cluster





