# Group 16

# Team members:

# Zenan Ji (Student ID: 1122396) - city: Nanjing

# Weijie Ye (Student ID: 1160818) - city: Fuzhou

# Wenqin Liu (Student ID: 807291) - city: Guangdong

# Jinhong Yong (Student ID: 1198833) - city: Kuala Lumpur

# Zixuan Zeng (Student ID: 1088297) - city: Melbourne

# use localhost to interact with the openstack API and to create resources
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files: 
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-sg
    - role: openstack-instance
    - role: openstack-volume-snapshot