- hosts: Datanodes
  vars_files:
      - host_vars/nectar.yaml
  vars:
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: ubuntu
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      http_proxy: "http://wwwproxy.unimelb.edu.au:8000/"
      current_ip: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
      node1_domain: 'couchdb1.test.com'
      node2_domain: 'couchdb2.test.com'
      node3_domain: 'couchdb3.test.com'
      nodes_domain:
        - ip: "{{hostvars[groups['DataNodes'][0]]['ansible_default_ipv4']['address']}}"
          domain: "{{node1_domain}}"
        - ip: "{{hostvars[groups['DataNodes'][1]]['ansible_default_ipv4']['address']}}"
          domain: "{{node2_domain}}"
        - ip: "{{hostvars[groups['DataNodes'][2]]['ansible_default_ipv4']['address']}}"
          domain: "{{node3_domain}}"
      masternode: "{{hostvars[groups['DataNodes'][0]]['ansible_default_ipv4']['address']}}" 
      couchdb_docker_network: couchdb
      script_folder: /scripts
      code_path: /code
      harvester_image_build_path: "{{code_path}}/docker_image"
      code_version: master ## can set to branch name or hash value of any commit

  roles:
    - role: couchdb_replicate
   
      
   


