# install dependencis on the host pip
- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  pip:
    name: ['pip']
    state: latest
    
- name: Install openstack sdk
  pip:
    name: ['openstacksdk==0.52.0']
    state: latest
