---
# - name: Shut down docker previous server
#   become: yes
#   shell: docker-compose down --rmi local
#   args:
#     chdir: '/home/ubuntu/COMP90024/COMP90024Group16/TwitterHarvester/tweepy'

- name: Shut down previous server
  become:
    yes
  shell: docker-compose down -d
  args:
    chdir: '/home/ubuntu/COMP90024/COMP90024Group16/TwitterHarvester/tweepy'

- name: Remove directory __pycache__
  become: 
    yes
  file:
    path: '/home/ubuntu/COMP90024/COMP90024Group16/TwitterHarvester/tweepy/__pycache__'
    state: absent

- name: Remove directory
  file:
    path: /home/ubuntu/COMP90024
    state: absent

- name: creates directory
  file:
    path: '/home/ubuntu/COMP90024'
    state: directory

- name: git clone repo
  shell: git clone https://github.com/williamjz/COMP90024Group16.git
  args:
    chdir: '/home/ubuntu/COMP90024'

- name: git pull lastest repo
  shell: git pull
  args:
    chdir: '/home/ubuntu/COMP90024/COMP90024Group16'
    
- name: copy spider config to hosts
  copy:
    src: 'configs/spiderSetting.py'
    dest: '/home/ubuntu/COMP90024/COMP90024Group16/TwitterHarvester/tweepy'

- name: Start server
  become:
    yes
  shell: docker-compose up -d
  args:
    chdir: '/home/ubuntu/COMP90024/COMP90024Group16/TwitterHarvester/tweepy'

# - name: Run docker compose
#   become: yes
#   docker_compose:
#     project_src: '/home/ubuntu/COMP90024/COMP90024Group16/TwitterHarvester/tweepy'
#     pull: false
#     build: yes
#     state: present
#     remove_orphans: no
#     recreate: always