---
- name: update apt
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: install packages
  become: yes
  apt:
    name: ['software-properties-common','git','vim','python-docker','curl','unzip',''python-pip'']
    state: latest
    install-recommends: no
    update_cache: yes



