# Group 16

# Team members:

# Zenan Ji (Student ID: 1122396) - city: Nanjing

# Weijie Ye (Student ID: 1160818) - city: Fuzhou

# Wenqin Liu (Student ID: 807291) - city: Guangdong

# Jinhong Yong (Student ID: 1198833) - city: Kuala Lumpur

# Zixuan Zeng (Student ID: 1088297) - city: Melbourne
---

# Stop existing Couch DB Docker containers and remove them (if any)
- name: Stop CouchDB Docker container
  become: yes
  docker_container:
    name: couchdb
    state: absent

# Create new docker container for CouchDB and start container
- name: Create and start CouchDB Docker container
  become: yes
  docker_container:
    name: couchdb
    image: "ibmcom/couchdb3:{{ VERSION }}"
    state: started
    recreate: true
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /volume/couchdb/data
    pull: yes
    env:
      COUCHDB_USER: "{{ user }}"
      COUCHDB_PASSWORD: "{{ pass }}"
      COUCHDB_SECRET: "{{ cookie }}"
      ERL_FLAGS: "-setcookie \"{{ cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""