---
- name: setup couchdb cluster | step 1
  become: yes
  uri:
    url: http://{{ groups['Masternode'][0] }}:{{couchdb_port}}/{{ cluster_name }}
    status_code: 201
    method: POST
    user: "{{ user }}"
    password:  "{{ pass }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\
             \"username\": \"{{ user }}\", \"password\":\"{{ pass }}\", \"port\": \"{{couchdb_port}}\",\
             \"remote_node\": \"{{ item }}\", \"node_count\": \"{{ groups['database'] | length }}\",\
             \"remote_current_user\":\"{{ user }}\", \"remote_current_password\":\"{{ pass }}\"}"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['Workernode'] }}"

- name: setup couchdb cluster | step 2
  become: yes
  uri:
    url: http://{{ groups['Masternode'][0] }}:{{couchdb_port}}/{{ cluster_name }}
    status_code: 201,409
    method: POST
    user: "{{ user }}"
    password:  "{{ pass }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"add_node\", \"host\":\"{{ item }}\",\
             \"port\": \"{{ couchdb_port }}\", \"username\": \"{{ user }}\", \"password\":\"{{ pass }}\"}"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['Workernode'] }}"

- name: setup couchdb cluster | step 2.5
  become: yes
  uri:
    url: http://{{ groups['Masternode'][0] }}:{{couchdb_port}}/
    status_code: 200,201,409
    method: GET
    user: "{{ user }}"
    password:  "{{ pass }}"
    force_basic_auth: yes
    return_content: yes


- name: steup couchdb cluster | step 3 -- finish
  become: yes
  uri:
    url: http://{{ groups['Masternode'][0] }}:{{ couchdb_port }}/{{ cluster_name }}
    status_code: 201
    method: POST
    user: "{{ user }}"
    password:  "{{ pass }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"finish_cluster\"}"
    headers:
      Content-Type: "application/json"
